### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by dutchpatriot** [iandouglas96/engravR#2]
Hi when I test run the program I get this error?

  File "./laserengraver", line 188, in <module>
    old_x_pos=x_pos;
NameError: name 'x_pos' is not defined

I googled for the answer but I couldn't find anything.
Nice work on the remote by the way!
Greets,
Dutchpatriot

**Comment by iandouglas96** [comment]
My guess is that you are using a gcode file not generated by Inkspace gcodetools, so the format isn’t quite what the software is expecting.  The test file that Daniel Chai gives in his tutorial won’t work, because I rewrote some of his code to be able to handle gcodetools gcode files.  If you still can’t get it to work, let me know.

Ian

---------------------------------
Ian D. Miller
Lead Developer
http://www.pxlweavr.com

**Comment by dutchpatriot** [comment]
Indeed the file is not created by the Inkscape gcodetools but by the laserengraver-extension. http://www.slackersdelight.com/instructables/laserengraver.zip. It wouldn't work on 0.91 so I found this http://www.tylerforsythe.com/2015/02/inkscape-laser-engraver-bug/ this solved the creating of or lack of creating the Gcode file. I'll try to do it again with the Gcode tool from Inkscape. 

I'll report back.
By the way thanks again...
Marco aka Dutchpatriot

**Comment by dutchpatriot** [comment]
It looks like it works now!
Thanks...

**Comment by iandouglas96** [comment]
Great!
